version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true

      - run: 
          name : "Building Docker image with terraform and azure cli"
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo "Building version ${TAG}:"
            docker build -t terraform-azure-cli:$TAG -f /home/circleci/project/terraform-azure/Dockerfile .
            docker tag terraform-azure-cli:$TAG $DOCKERHUB_USER/terraform-azure-cli:$TAG
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
            docker push $DOCKERHUB_USER/buildah:$TAG
            echo "The image has been pushed in this repository => ${DOCKERHUB_USER}/terraform-azure-cli:${TAG}"
            rm -f /home/circleci/.docker/config.json