version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true

      # build and push Docker image
      - run: 
          name : "Building buildah image"
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $TAG
            echo "La ruta actual es la siguiente => $(pwd)"
            docker build -t buildah-circleci:$TAG -f /home/circleci/project/buildah/Dockerfile .
            docker tag buildah-circleci:$TAG $DOCKERHUB_USER/buildah:$TAG
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
            docker push $DOCKERHUB_USER/buildah:$TAG
            echo "La imagen ha sido subida correctamente al siguiente endpoint => ${DOCKERHUB_USER}/buildah:${TAG}"
            rm -f /home/circleci/.docker/config.json